version: '3'

volumes:
  mysql-data:

services:
  web-backend:
    build: ./11-training-php/configs/backend
    container_name: web-backend
    ports:
      - "8080:80"
    volumes:
      - ./11-training-php:/var/www/html
      - ./11-training-php/configs/backend/php.ini:/usr/local/etc/php/php.ini
      - ./11-training-php/configs/httpd_security.conf:/etc/apache2/conf-available/security.conf
    working_dir: /var/www/html
    environment:
      APP_ENV: local
    depends_on:
      - web-mysql
    restart: always

  web-mysql:
    container_name: web-mysql
    image: "mysql:5.7.43"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  web-phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - web-mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: web-mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

